language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'

install:
  - python setup.py install
  - django-admin.py startproject gdtest
  - /bin/cp -av test/settings.py gdtest/gdtest/
  - /bin/cp -av gdstorage/tests.py gdtest/gdtest/
  - /bin/cp -av test/ gdtest/

script:
  - cd gdtest && python manage.py test

before_install:
- openssl aes-256-cbc -K $encrypted_0a18e31b38f0_key -iv $encrypted_0a18e31b38f0_iv
  -in gdstorage.json.enc -out test/gdstorage.json -d
